'use strict'
const test = require('node:test')
const assert = require('node:assert/strict')
const crypto = require('node:crypto')
const { createPgStore } = require('./db')

test('PostgreSQL schema, ownership and approval rules', { skip: !process.env.DATABASE_URL }, async t => {
  const db = await createPgStore()
  t.after(() => db.close())
  const id = crypto.randomUUID()
  const otherId = crypto.randomUUID()
  const email = id + '@example.invalid'
  const user = await db.createUser({ id, email, passwordHash: 'testing' })
  assert.equal(user.email, email)
  assert.equal((await db.findUserByEmail(email)).id, id)
  assert.equal((await db.findUserByEmail(email)).emailVerifiedAt, null)
  const verifyToken = crypto.randomBytes(32).toString('hex')
  await db.saveAuthToken(id, 'email_verification', verifyToken, new Date(Date.now() + 60000))
  assert.equal(await db.consumeAuthToken(verifyToken, 'password_reset', 'password'), false)
  assert.equal(await db.consumeAuthToken(verifyToken, 'email_verification'), true)
  assert.equal(await db.consumeAuthToken(verifyToken, 'email_verification'), false)
  assert.ok((await db.findUserByEmail(email)).emailVerifiedAt)
  const resetToken = crypto.randomBytes(32).toString('hex')
  await db.saveAuthToken(id, 'password_reset', resetToken, new Date(Date.now() + 60000))
  const sessionToken = crypto.randomBytes(32).toString('hex')
  await db.createSession(sessionToken, id, new Date(Date.now() + 60000))
  assert.equal((await db.findSession(sessionToken)).id, id)
  await db.deleteSession(sessionToken)
  assert.equal(await db.findSession(sessionToken), null)
  await db.createSession(sessionToken, id, new Date(Date.now() + 60000))
  assert.equal(await db.consumeAuthToken(resetToken, 'password_reset', 'a-new-hashed-password'), true)
  assert.equal((await db.findUserByEmail(email)).passwordHash, 'a-new-hashed-password')
  assert.equal(await db.findSession(sessionToken), null, 'password resets revoke all user sessions')
  assert.equal(await db.consumeAuthToken(resetToken, 'password_reset', 'another'), false)

  const other = await db.createUser({ id: otherId, email: otherId + '@example.invalid', passwordHash: 'testing' })
  assert.ok(other)
  const artistId = String(Date.now()) + crypto.randomInt(1000, 9999)
  const profile = await db.createProfile(id, { artistId, artistName: 'Artist', proofCode: 'TEST-CLAIM' })
  assert.equal(profile.status, 'pending')
  assert.equal((await db.getProfile(id)).proofCode, 'TEST-CLAIM')
  const songId = crypto.randomUUID()
  const neteaseSongId = String(Date.now()) + crypto.randomInt(10000, 99999)
  const song = await db.createSong({
    id: songId, ownerId: id, neteaseSongId, title: 'Testing',
    artist: 'Artist', url: 'https://music.163.com/song?id=' + neteaseSongId,
  })
  assert.equal(song.status, 'pending')
  assert.equal((await db.listSongs()).some(s => s.id === songId), false)
  assert.equal(await db.approveSong(songId), null, 'unverified artists cannot publish')
  assert.equal((await db.reviewQueue()).profiles.some(p => p.userId === id), true)
  assert.ok(await db.approveProfile(id))
  assert.ok(await db.approveSong(songId))
  assert.equal((await db.recommendSongs(id)).some(s => s.id === songId), false, 'own songs excluded')
  assert.equal((await db.recommendSongs(otherId)).some(s => s.id === songId), true, 'unseen song recommended')
  assert.equal(await db.recordVisit(songId, id), null, 'self visit excluded')
  assert.equal(await db.recordVisit(songId, otherId), true)
  assert.equal(await db.recordVisit(songId, otherId), false, 'same account counted once')
  assert.equal((await db.recommendSongs(otherId)).some(s => s.id === songId), false, 'visited song no longer recommended')
  const publicSong = (await db.listSongs()).find(s => s.id === songId)
  assert.equal(publicSong.communityVisitors, 1)
})


test('PostgreSQL export scope and transactional account deletion', { skip: !process.env.DATABASE_URL }, async t => {
  const db = await createPgStore()
  t.after(() => db.close())
  const owner = crypto.randomUUID(), listener = crypto.randomUUID()
  const ownerEmail = owner + '@example.invalid'
  await db.createUser({ id: owner, email: ownerEmail, passwordHash: 'hash-not-exported' })
  await db.createUser({ id: listener, email: listener + '@example.invalid', passwordHash: 'secret' })
  const songId = crypto.randomUUID()
  const stamp = Date.now() + crypto.randomInt(100000, 999999)
  await db.createProfile(owner, { artistId: String(stamp), artistName: 'Privacy Test', proofCode: 'PRIVACY-CODE' })
  await db.createSong({ id: songId, ownerId: owner, neteaseSongId: String(stamp + 1000000),
    title: 'Privacy Song', artist: 'Privacy Test', url: 'https://music.163.com/song?id=' + (stamp + 1000000) })
  await db.approveProfile(owner)
  await db.approveSong(songId)
  await db.recordVisit(songId, listener)
  await db.addAudit('profile_approved', owner)
  await db.addAudit('song_approved', songId)
  const exported = await db.exportAccount(owner)
  assert.equal(exported.account.email, ownerEmail)
  assert.equal(exported.submittedSongs.length, 1)
  assert.equal(exported.artistProfile.artistName, 'Privacy Test')
  assert.equal(exported.visitedSongs.length, 0)
  assert.equal(JSON.stringify(exported).includes('hash-not-exported'), false)
  const listenerData = await db.exportAccount(listener)
  assert.equal(listenerData.submittedSongs.length, 0)
  assert.equal(listenerData.visitedSongs.length, 1)
  const sessionToken = crypto.randomBytes(32).toString('hex')
  await db.createSession(sessionToken, owner, new Date(Date.now() + 60000))
  await db.revokeAllSessions(owner)
  assert.equal(await db.findSession(sessionToken), null)
  await db.createSession(sessionToken, owner, new Date(Date.now() + 60000))
  assert.equal(await db.deleteAccount(owner), true)
  assert.equal(await db.exportAccount(owner), null)
  assert.equal(await db.findSession(sessionToken), null)
  assert.equal((await db.listSongs()).some(song => song.id === songId), false)
  assert.equal((await db.exportAccount(listener)).visitedSongs.length, 0)
  assert.equal(await db.deleteAccount(owner), false)
  // Deletion frees the artist ID and email while retaining unrelated accounts.
  assert.ok(await db.findUserByEmail(listener + '@example.invalid'))
})
